### ISSUE TITLE
自动退出结束进程

### ISSUE THREAD

**Issue by luomouren** [greatbsky/react-native-pull#10]
debug在真机上调试，打开app一段时间，老是自己退出。

**Comment by luomouren** [comment]
自己结束进程

**Comment by greatbsky** [comment]
周末调试看看~~~

**Comment by greatbsky** [comment]
新发布了version 2.0.0，做了很多改动，目前为止没有发现自动结束进程的问题，有问题再反馈吧

**Comment by onlybenyang** [comment]
确实有这个问题

**Comment by onlybenyang** [comment]
在debug模式的android真机上，超过一定时间（时间不确定）后不操作手机，应用会自动退出；IOS没有测试过
