### ISSUE TITLE
第一次进入push的时候,不回弹

### ISSUE THREAD

**Issue by dailinyi** [greatbsky/react-native-pull#12]
很感谢作者的付出
发现了一个问题,使用PullList 当第一次上拉完成的时候 画面会卡在上拉界面完成拖拽的位置  不会回弹到列表底部  
而第二次以及以后 就可以了

试过ListView 是没有这个问题的

望解决或者提供解决思路  谢谢~

**Comment by dailinyi** [comment]
备注
在IOS上出现的问题
因手头没有安卓测试机
所以暂且无法确定 安卓是否会有此问题

**Comment by coocoda** [comment]
确实，应该是ios上会有，android上暂时未发现。

**Comment by greatbsky** [comment]
周末我调试看看，谢谢反馈~~~

**Comment by greatbsky** [comment]
新发布了version2.0.0，看还有问题么？

**Comment by dailinyi** [comment]
It's OK
