### ISSUE TITLE
pulllist 完成数据加载　下拉刷新的ｈｅａｄｅｒ　不收回？

### ISSUE THREAD

**Issue by hu8373551** [greatbsky/react-native-pull#13]
pulllist 完成数据加载　下拉刷新的ｈｅａｄｅｒ　不收回？

**Comment by hu8373551** [comment]
resolve()　做了什么处理？

**Comment by greatbsky** [comment]
this.props.onPullRelease(this.resetDefaultXYHandler); 方法resetDefaultXYHandler重置状态 重置位置
