### ISSUE TITLE
使用PullView报错

### ISSUE THREAD

**Issue by yuxichina** [greatbsky/react-native-pull#15]
@react-native  0.39.2

报错信息：
View was rendered with explicitly set width/height but with a 0 flexBasis. ....

请看一下这个是什么问题？
没升级版本之前是没问题的。

**Comment by naivehhr** [comment]
暂解：
实例代码中 topIndicatorRender(或自定义topIndicatorRender方法)return <View style={{flex: 1  改成
flexGrow: 1

**Comment by greatbsky** [comment]
感谢@naivehhr 的回复，@yuxichina 新版react-native-pull Version1.1.4已经修复了。有问题再反馈~~
