### ISSUE TITLE
如果数据没有一屏的话,一进入界面就会出现菊花加载?

### ISSUE THREAD

**Issue by shaoting0730** [greatbsky/react-native-pull#19]
如果数据没有一屏的话,一进入界面就会出现菊花加载?这个怎么处理?

**Comment by greatbsky** [comment]
你貌似说的是react-native-pull-demo，这个是数据问题this.dataSource设置多点数据即可

**Comment by shaoting0730** [comment]
额.那后台数据只有那么少,不够一屏怎么办?

**Comment by greatbsky** [comment]
@pheromone  那就将renderFooter属性去掉，这个PullList属性跟ListView是相同的，具体可以参考下官网手册
