### ISSUE TITLE
使用中遇到的几点建议和问题。

### ISSUE THREAD

**Issue by AnyGong** [greatbsky/react-native-pull#2]
很感谢作者的付出，我狠想用这个效果。目前使用中有几点疑问：
1. 界面正在刷新的过程中，用户继续（上/下)拉的时候，界面的顶部立即回到初始状态了。（此处是否合应该重新计算，模拟用户的上/下拉回到初始状态）
2. 界面正在刷新的过程中，用户继续（上/下)达到顶部的时候，假设此时Indicator还在loading和数据正在async中，用户如再次下拉，此时的Indicator不见了，应该是还在刷新中？
3. 都是参照qq的刷新效果来看的，说的不对请见谅

**Comment by greatbsky** [comment]
这个bug是因为在下拉过程中，外部调用了resolve()会触发topindicator回到顶部，已经在V1.0.13中修改了。
谢谢反馈！

**Comment by greatbsky** [comment]
fixed in version v1.0.13, close this issue.

**Comment by hu8373551** [comment]
resolve()　做了什么处理？

**Comment by greatbsky** [comment]
this.props.onPullRelease(this.resetDefaultXYHandler); 方法resetDefaultXYHandler就是重置状态，重置位置
