### ISSUE TITLE
我在Android下使用onPushing方法的时候，并不总是会被调用，拖动的时候经常就没效果了

### ISSUE THREAD

**Issue by yangankang** [greatbsky/react-native-pull#20]

**Comment by greatbsky** [comment]
你是下拉后，接着往上推后发现onPushing没有调用么？
拖动的时候经常就没效果了是指的什么没有效果？最好有截图上传下~

**Comment by yangankang** [comment]
这个不好截图，我是想做一个背景透明的头部搜索框，然后往下拉的时候根据y的值改变头的透明度，类似天猫那种，但是拖着拖着就没效果了，调试发现onPushing这个方法还拖动的时候已经没有执行了(差不多执行了一半)，后来我直接继承PullView重写那个含有ScrollView的方法用onScroll 是没有问题的(貌似拖动的时候背景变化感觉卡)

然后我发现还缺一事件方法：就是我要刷新的时候往下拉需要隐藏头部，刷新结束之后显示头部，但是如果我没有拉到刷新而是拉到一半松手了，头没有了，我需要一个在txtPullok时放弃刷新的事件回调

谢谢

**Comment by greatbsky** [comment]
关于拖动的时候背景变化感觉卡的问题，建议你调用setNativeProps方法设置透明度
关于放弃刷新的事件回调，你临时修改下此项目代码吧，最近有点忙，有需要的话可以协助下~~~

**Comment by yangankang** [comment]
我已经把代码拿出来修改了，IOS模拟器性能差很多决定用原生的下拉刷新，非常感谢也希望你能多做一些开源的组件，新年快乐

**Comment by greatbsky** [comment]
Happy new year~~
