### ISSUE TITLE
没法用scrollTo这个方法

### ISSUE THREAD

**Issue by wubangshun** [greatbsky/react-native-pull#23]
ExceptionsManager.js:63 this.refs.listView.scrollTo is not a function

**Comment by greatbsky** [comment]
你这是报错了么？android? ios?
this.refs.listView.scrollTo 哪来的？

**Comment by Silence0928** [comment]
你好 请问这个问题解决了吗   我现在想要让列表滚动到最顶部  但是要怎样去实现呢

**Comment by greatbsky** [comment]
貌似你需要修改这里的代码https://github.com/greatbsky/react-native-pull/blob/master/PullList.js
PullList 目前没有提供scrollTo 方法，临时先修改以上文件的代码提供一个scrollTo 方法吧，下一个版本会增加这个方法(估计得年后了)。

**Comment by Silence0928** [comment]
好的   谢谢大佬  提前祝新年快乐哇

**Comment by WilliamThh** [comment]
@greatbsky 我这边在实例化pullList对象后ref={(pullList) => { this.pullList = pullList}} ，this.pullList同样调用scrollTo这个方法报错undefined

**Comment by greatbsky** [comment]
同样的问题，看起来scrollTo用的人还挺多的，最近几天有点忙，所以不能更新版本，可以在https://github.com/greatbsky/react-native-pull/blob/master/PullList.js 里增加scrollTo方法，方法里再调用this.scroll.scrollTo方法即可.
@ChuckyThh

**Comment by WilliamThh** [comment]
@greatbsky 好的，我试试，谢谢啦

**Comment by wubangshun** [comment]
坐等更新

**Comment by WilliamThh** [comment]
@wubangshun 这个可以自己添加，我觉得上拉卡顿才是首要解决的问题>..<

**Comment by greatbsky** [comment]
谢谢各位反馈，新发布了新版本v2.0.2，兼容RN 0.42.0，也增加了几个方法，各位可以试试。

因个人精力有限，希望对此项目有兴趣的童鞋参与项目编码，有意向的欢迎加入QQ群：558136654 RN开源项目协作。
