### ISSUE TITLE
国际化语言包出错

### ISSUE THREAD

**Issue by whatlife** [greatbsky/react-native-pull#25]
![国际话报错？](http://wx1.sinaimg.cn/large/602cf753gy1fcj8dwrqnnj207v079mxp.jpg)

如图

**Comment by whatlife** [comment]
发现这个问题应该是该插件不支持RN的最新版本0.41.0，
我如果用 RN0.40.0版本，就不会出现这个问题。

**Comment by greatbsky** [comment]
谢谢反馈，新发布了新版本v2.0.2，兼容RN 0.42.0。语言包问题也不报错了~~~

因个人精力有限，希望对此项目有兴趣的童鞋参与项目编码，有意向的欢迎加入QQ群：558136654 RN开源项目协作。
