### ISSUE TITLE
0.41.2下无法上拉滚动

### ISSUE THREAD

**Issue by lataing** [greatbsky/react-native-pull#27]
滚动的功能无效了。

**Comment by RealAmissio** [comment]
同上

**Comment by chuyik** [comment]
一样...

**Comment by chuyik** [comment]
这个问题在0.40不会出现，应该就是0.41才会发生

**Comment by greatbsky** [comment]
新发布了新版本v2.0.2，兼容RN 0.42.0。

因个人精力有限，希望对此项目有兴趣的童鞋参与项目编码，有意向的欢迎加入QQ群：558136654 RN开源项目协作。
