### ISSUE TITLE
我这边根本不能用

### ISSUE THREAD

**Issue by hxkuan** [greatbsky/react-native-pull#29]
![image](https://cloud.githubusercontent.com/assets/16953319/23355480/d90dac30-fd10-11e6-9f0a-e2efb0eaad9c.png)
我这边根本不能用，向上滚动后，向下滚动就直接下拉了

**Comment by hxkuan** [comment]
用的是模拟器

**Comment by greatbsky** [comment]
新发布了新版本，兼容RN 0.42.0

因个人精力有限，希望对此项目有兴趣的童鞋参与项目编码，有意向的欢迎加入QQ群：558136654 RN开源项目协作。

**Comment by greatbsky** [comment]
试试v2.0.2吧，有问题再反馈，close issue
