### ISSUE TITLE
用pullList遮住了前面相邻的组件

### ISSUE THREAD

**Issue by jinleli** [greatbsky/react-native-pull#3]
react [native新人，使用pullList的时候上面写的返回按钮被遮住了`<Top navigator={this.props.navigator}/>
                <PullList onPullRelease={this.onPullRelease} dataSource={this.state.dataSource} renderRow={this.renderRow.bind(this)} style={styles.list} enableEmptySections = {true}/>
`不知道这个应该怎么解决啊

**Comment by greatbsky** [comment]
please post your code and upload the capture of app.
I guess some cause:
1. the **position** of Top compnent
2. modify the value of style **zIndex**

**Comment by jinleli** [comment]
您好，我再检查了下把我的Top组件包裹在View组件里面就能显示了，我的Top组件如下
`<TouchableHighlight onPress={this._propReturn.bind(this)} style={styles.top} >
                 <Image source={require('../../images/nav_icon/back.png')} style={styles.top_img} />
            </TouchableHighlight>`
我试了试在本来的Top里面包裹一层View,不起作用，但是在引用时包裹才起作用如下
`<View style={styles.container}>             
                    <View><Top navigator={this.props.navigator}/></View>
                    <PullList onPullRelease={this.onPullRelease} dataSource={this.state.dataSource} renderRow={this.renderRow.bind(this)} style={styles.list} enableEmptySections = {true}/>
                </View>`
不知道是什么原因造成的，难道PullList前面只能放RN里面原有的组件吗，不管什么原因目前我的问题解决了，谢谢您的回复

**Comment by greatbsky** [comment]
估计跟你的styles.top_img styles.top样式相关~~~或者你试试原来的代码把PullList换成有边框的View试试你说的问题有重现没有

**Comment by greatbsky** [comment]
没问题就把这个issue关了~~~
