### ISSUE TITLE
loadMore怎么强制关闭。刷新界面

### ISSUE THREAD

**Issue by gwokwong** [greatbsky/react-native-pull#7]
怎么在load more()中强制关闭上拉出来的加载提示的界面。我想在没有网络情况下直接关闭。

```
loadMore() {
    setTimeout(() => {
        this.setState({
            refreshing:false,
            nomore:true,
        });
    }, 1000);
}
```

<View style={styles.container2}>
                <PullList dataSource={this.state.dataSource} enableEmptySections={true}
                          renderRow={(rowData) =>
                              (
                                  <TouchableOpacity style={[styles.item, styles.row]}
                                                    onPress={this._showDetail.bind(this, rowData.url, rowData.title)}>
                                      <View>
                                          <Image style={styles.img} source={{uri: rowData.img}} resizeMode="cover"/>
                                      </View>
                                      <View style={styles.text}>
                                          <Text style={styles.title} numberOfLines={4}>{rowData.title}</Text>
                                      </View>
                                  </TouchableOpacity>
                              )
                          } onPullRelease={this.onPullRelease} topIndicatorRender={this.topIndicatorRender}
                          topIndicatorHeight={30} onEndReached={this.loadMore} onEndReachedThreshold={50} renderFooter={this.renderFooter} />
            </View>

**Comment by greatbsky** [comment]
PullList是基于ListView封装的，onEndReached={this.loadMore}方法也是同ListView，要实现你说的功能，需要你自己在this.loadMore方法中增加state做判断。

**Comment by greatbsky** [comment]
不是bug，若没其他问题，将此issue关闭了。
