### ISSUE TITLE
不知道为什么 滑动的时候ListView不停在重绘

### ISSUE THREAD

**Issue by xiaoxuez** [greatbsky/react-native-pull#8]
当数据条目很少 并且能够滑动的时候，然后滑动ListView  renderRow就会不停被调用 

   如果是我代码有问题  请指出 谢谢。 我的版本是0.28   安卓环境

   ` constructor(props){
      super(props);
      this.state = {
        dataSource : new ListView.DataSource({
           rowHasChanged: (r1, r2) => r1 !== r2,
        }),
      }
    }
    componentDidMount(){
      let dataBlob = [];
      for (var ii = 0; ii < 4; ii++) {
        dataBlob.push('Row ' + ii);
      }
      this.setState({
        dataSource: this.state.dataSource.cloneWithRows(dataBlob),
      });
    }
   _renderRow(deviceLogInfo, sectionID: number, rowID: number){
       return(
         <View 
             style={{backgroundColor: 'red',width: 360,height: 170,marginTop: 30}} />
      )
  }

   render(){
      return(
        <View style={{flex: 1,backgroundColor: 'white'}}>
          <PullList
            dataSource={this.state.dataSource}
            renderRow={this._renderRow.bind(this)}
            onPullRelease={() =>{}}
            />
        </View>
      )
    }`

**Comment by greatbsky** [comment]
是不是跟componentDidMount有关系？把这个方法重命名下，然后放constructor里调用试试~~~

**Comment by xiaoxuez** [comment]
恩恩  要是在render之前准备好数据就不会导致重绘，但是我现在肯定是需要下拉刷新之类的 有关数据重新加载的过程的，所以很奇怪 我也看不出是哪里的问题

**Comment by xiaoxuez** [comment]
恩  加上了initialListSize={1}  设置较小值   就能解决我的问题了  但是不知道为什么..

**Comment by xiaoxuez** [comment]
因为我的ListView做的有点复杂  有很多会重绘的情况，然后后来发现问题是Pullable的onLayout有点问题，在不停调用，然后时间问题我就没看原因了，只做了一丢丢小的处理，
  if (this.state.width !== e.nativeEvent.layout.width || this.state.height !== ) e.nativeEvent.layout.height {
        this.setState({
          width: e.nativeEvent.layout.width,
          height: e.nativeEvent.layout.height,
        });
      }  加了一层判断，避免了不停setState

**Comment by greatbsky** [comment]
@xiaoxuez 感谢回复，我修改下代码，增加这个判断吧。谢谢

**Comment by greatbsky** [comment]
version 1.1.2已经修改，可以重新执行下 npm install react-native-pull --save
